### ISSUE TITLE
pickadate definitions are duplicated

### ISSUE THREAD

**Issue by vvakame** [borisyankov/DefinitelyTyped#3078]
https://github.com/borisyankov/DefinitelyTyped/blob/master/pickadate/pickadate.d.ts
https://github.com/borisyankov/DefinitelyTyped/blob/master/jquery.pickadate/jquery.pickadate.d.ts

**Comment by theodorejb** [comment]
We really should standardize on one set of definitions per library. Otherwise it leads to confusion and overall decreased definition quality.

I ran the jquery.pickadate tests (based directly on the Pickadate library documentation) against the pickadate definitions and found that a number of very basic tests are failing:

1. The `hiddenName` option should accept a boolean, not a string.
2. The `formatLabel` time option should accept a function as well as a string.
3. `picker.get()` (short for `picker.get('value')`) is not supported.
4. `picker.set()` does not support setting options without a value (e.g. `picker.set('clear')`).
5. `picker.on()` should support passing an object in addition to a method name.
6. `picker.trigger()` should support passing a data object.

The jquery.pickadate tests are much more thorough and accurate in testing library functionality, so my recommendation is that the pickadate definitions be removed in favor of jquery.pickadate.
