### ISSUE TITLE
Should jquery attr also accept boolean?

### ISSUE THREAD

**Issue by xt0rted** [borisyankov/DefinitelyTyped#4797]
I'm trying to assign a `boolean` value to an attribute like so
``` ts
$('#myElement').attr('aria-visible', true);
```
This is a common way of setting some of the `aria-` attributes but since the `attr()` functions only accept `string` or `number` I get a compile error.

Should these functions be updated to also accept `boolean`?

**Comment by vvakame** [comment]
@xt0rted please send a pull request. I'll review it. @johnnyreilly

**Comment by johnnyreilly** [comment]
Hi @xt0rted,

Because [officially jQuery does not support boolean](http://api.jquery.com/attr/#attr-attributeName-value) values for `attr` we wouldn't look to change this in Definitely Typed. We strive to be API compliant where a well defined API exists (as it does with jQuery).

If you'd like to raise a PR with the [jQuery API docs](https://github.com/jquery/api.jquery.com) and it's taken then we'd certainly look to merge a PR which changed the typings after that.  We've done this in the past on a number of occasions.

Best,
John
