### ISSUE TITLE
angularjs.TypeScript.DefinitelyTyped includes an ancient version of jquery.d.ts

### ISSUE THREAD

**Issue by mbraude** [borisyankov/DefinitelyTyped#5446]
See this stack overflow post:

http://stackoverflow.com/questions/32088619/angularjs-definitely-typed-visual-studio-2015/32111765#32111765

If you add this package to a TypeScript project in Visual Studio and then reference it, you'll see hundreds of compiler errors. The reason why is because the d.ts file for jQuery appears to be ancient. For example, it uses "bool" instead of "boolean".

I was able to fix it by upgrading the jQuery package, or adding jQuery.TypeScript.DefinitelyTyped to the project, which replaced the old version with a new one that was correct.

**Comment by vvakame** [comment]
@staxmanade ?

**Comment by staxmanade** [comment]
This is the first I've heard about the issue.

In the `.nuspec` definition we place package dependencies like `angularjs` depends on `jquery` and it uses the following format to define it's dependencies

`"<dependency id=`"$dependentPackageName`" />"`

Note there is no version specified and on this page https://docs.nuget.org/create/versioning#Specifying-Version-Ranges-in-.nuspec-Files it says `empty = latest version.` so it should be pulling the most recent jquery version...

What happens if you remove `jquery.Typings.DefinitelyTyped` and install from scratch?

Hmmm

**Comment by ivanoxq** [comment]
I just tested it and the issue is when you installed angularjs.typescript.definitelytyped 4.1.4, it apperantly says it needs jquery.Typings.DefinitelyTyped 0.1 version and install that instead of the latest version.

I uninstall the angularjs.typescript.definitelytyped, then it showed the latest jquery.Typings.DefinitelyTyped version and so I installed it. Afterwards I installed angularjs.typescript.definitelytyped

**Comment by xt0rted** [comment]
I've run into this a few times as well. It's due to the NuGet package manager UI in Visual Studio 2015 changing the dependency behavior from prior versions. It used to grab the most recent version (stable or prerelease depending on your settings) but now it lets you pick from
- Ignore Dependencies
- Lowest (default, at least on my machine)
- Highest Patch
- Highest Minor
- Highest

Since versions aren't specified for the dependencies this is why the first jquery release is being used instead of the most recent.

**Comment by mbraude** [comment]
You might want to comb through the other Nuget packages which have dependencies on other libraries and make similar changes to whatever you do here.

**Comment by nrice** [comment]
I just ran into this issue on vs2015.  jquery.Typings.DefinitelyTyped was version 001.  I upgraded it to latest stable, errors disappeared.

**Comment by dawud-tan** [comment]
does this issue still occur?

**Comment by staxmanade** [comment]
# :white_check_mark: :white_check_mark: :white_check_mark: Answer :white_check_mark: :white_check_mark: :white_check_mark: 

For anyone running into this issue: check the following setting in Visual Studio:

![image](https://cloud.githubusercontent.com/assets/156715/10861918/92beaf8e-7f50-11e5-9ef0-ca87aa8f5d12.png)

The default behavior may not have been “Lowest” before which may explain why this issue is new to Visual Studio 2015.  To get things to work with the current angular TS definition package, you need to  choose "highest" when you install or upgrade your package.
