### ISSUE TITLE
how to write definitions with es6 modules if library emits to window?

### ISSUE THREAD

**Issue by stepancar** [borisyankov/DefinitelyTyped#5797]
Hello @jbrantly, @basarat and others!
Darkroomjs emits to window self constructor.
```javascript
var Darkroom = function(){
    // any code
}
window.Darkroom = Darkroom ;
```
i wrote [definitions](https://github.com/borisyankov/DefinitelyTyped/pull/5784/files) for it.
you can see test. it works fine if used <//reference
but i need import Darkroom like this
``` javascript
   import {Darkroom} from 'darkroomjs';
   var inst = new Darkroom('#test');
```
i tryed like this
```javascript
import * as Darkroom from 'darkroomjs';
var inst = new ((window as any).Darkroom as Darkroom)('#test');
``` 
but catch compiler error "can't not find name Darkroom"

Please help me.
Thank you!

**Comment by stepancar** [comment]
if you want - i can add repo

**Comment by basarat** [comment]
The code `import {Darkroom} from 'darkroomjs';`  is designed to support *the package author's intent to publish on NPM. Since the package is not on NPM: 

![image](https://cloud.githubusercontent.com/assets/874898/9839652/3091c798-5ac4-11e5-97b6-9e9d4dd3de30.png)

The package author needs to be informed about how to publish before `declare module "darkroomjs"` would be an acceptable PR :wink: 

If library only emits to `window` then ES6 module import cannot be supported in the definition. 

PS: please open a PR in future as it makes the code review *in place* easier :rose:

**Comment by stepancar** [comment]
Thank you, @basarat
